- name: Requirements
  remote_user: root
  apt: name={{ item }} state=present
  with_items:
    - curl
    - ca-certificates
    - gnupg

- name: PGDG Config
  remote_user: root
  shell: |
    curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - &&
    echo "deb http://apt.postgresql.org/pub/repos/apt/ buster-pgdg main"\
    > /etc/apt/sources.list.d/pgdg.list

- name: PostgreSQL Software
  remote_user: root
  apt: name=postgresql-13 state=present update_cache=yes

- name: PostgreSQL postgresql.conf
  vars:
    listen_addresses: '*'
    port: 5000
    max_connections: 30
    ram_memory: 1024
  template:
    src: postgresql.conf.j2
    dest: /etc/postgresql/13/main/postgresql.conf
    owner: postgres
    group: postgres
    mode: '0644'

- name: PostgreSQL pg_hba.conf
  vars:
    database: 'all'
    role: 'all'
    address: '192.168.1.101/24'
    method: 'scram-sha-256'
  template:
    src: pg_hba.conf.j2
    dest: /etc/postgresql/13/main/pg_hba.conf
    owner: postgres
    group: postgres
    mode: '0640'

- name: PostgreSQL restart
  remote_user: root
  shell: systemctl restart postgresql

- name: PostgreSQL upload vagrant.sql
  vars:
    user_name: vagrant
    user_password: "'vagrant'"
  template:
    src: vagrant.sql.j2
    dest: /tmp/vagrant.sql
    owner: postgres
    group: postgres
    mode: '0740'

- name: PostgreSQL exec vagrant.sql
  shell: |
    sudo su postgres -c "psql -f /tmp/vagrant.sql > /tmp/vagrant.log 2> /tmp/vagrant.log" &&
    rm /tmp/vagrant.sql
